# -*- coding: utf-8 -*-
"""CURC project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mXGkJ3CnJDFqPZ9Ml6aRRZACk9kSsR-0
"""

# https://www.kaggle.com/tanmoyx/covid19-patient-precondition-dataset?select=covid.csv
# sex: Female - 1, Male - 2
# patien_type:Outpatient - 1, Inpatient - 2
# intubed:Yes - 1, No - 2, Data missing or NA - 97,98,99
# pneumonia:Yes - 1, No - 2, Data missing or NA - 97,98,99
# age Yes - 1, No - 2, Data missing or NA - 97,98,99
# pregnancy Yes - 1, No - 2, Data missing or NA - 97,98,99
# diabetes Yes - 1, No - 2, Data missing or NA - 97,98,99
# copd Yes - 1, No - 2, Data missing or NA - 97,98,99
# asthma Yes - 1, No - 2, Data missing or NA - 97,98,99
# inmsupr Yes - 1, No - 2, Data missing or NA - 97,98,99
# hypertension Yes - 1, No - 2, Data missing or NA - 97,98,99
# other_disease Yes - 1, No - 2, Data missing or NA - 97,98,99
# cardiovascular Yes - 1, No - 2, Data missing or NA - 97,98,99
# obesity Yes - 1, No - 2, Data missing or NA - 97,98,99
# renal_chronic Yes - 1, No - 2, Data missing or NA - 97,98,99
# tobacco Yes - 1, No - 2, Data missing or NA - 97,98,99
# contact_other_covid Yes - 1, No - 2, Data missing or NA - 97,98,99
# covid_res Positive - 1, Negative - 2, Awaiting Results - 3
# icu Yes - 1, No - 2, Data missing or NA - 97,98,99

import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import numpy as np


from sklearn import datasets
from sklearn.tree import DecisionTreeRegressor

# read data
df = pd.read_csv('covid.csv')

df.head()

df.columns

df.describe()

# missing values
# avoid acciendentally delete ages = 97,98,99

#intubed
df=df[df['intubed']!=99]
df=df[df['intubed']!=98]
df=df[df['intubed']!=97]

#pneumonia
df=df[df['pneumonia']!=99]
df=df[df['pneumonia']!=98]
df=df[df['pneumonia']!=97]

#pregnancy
df=df[df['pregnancy']!=99]
df=df[df['pregnancy']!=98]
df=df[df['pregnancy']!=97]

#diabetes
df=df[df['diabetes']!=99]
df=df[df['diabetes']!=98]
df=df[df['diabetes']!=97]

#copd
df=df[df['copd']!=99]
df=df[df['copd']!=98]
df=df[df['copd']!=97]

#asthma
df=df[df['asthma']!=99]
df=df[df['asthma']!=98]
df=df[df['asthma']!=97]

#inmsupr
df=df[df['inmsupr']!=99]
df=df[df['inmsupr']!=98]
df=df[df['inmsupr']!=97]

#hypertension
df=df[df['hypertension']!=99]
df=df[df['hypertension']!=98]
df=df[df['hypertension']!=97]

#other_disease
df=df[df['other_disease']!=99]
df=df[df['other_disease']!=98]
df=df[df['other_disease']!=97]	

#cardiovascular
df=df[df['cardiovascular']!=99]
df=df[df['cardiovascular']!=98]
df=df[df['cardiovascular']!=97]

#obesity
df=df[df['obesity']!=99]
df=df[df['obesity']!=98]
df=df[df['obesity']!=97]

#renal_chronic	
df=df[df['renal_chronic']!=99]
df=df[df['renal_chronic']!=98]
df=df[df['renal_chronic']!=97]

#tobacco
df=df[df['tobacco']!=99]
df=df[df['tobacco']!=98]
df=df[df['tobacco']!=97]

#contact_other_covid
df=df[df['contact_other_covid']!=99]
df=df[df['contact_other_covid']!=98]
df=df[df['contact_other_covid']!=97]

#covid_res
df=df[df['covid_res']!=99]
df=df[df['covid_res']!=98]
df=df[df['covid_res']!=97]

#icu
df=df[df['icu']!=99]
df=df[df['icu']!=98]
df=df[df['icu']!=97]

df.head()
df.describe()

# original!
# missing values
#missing_values = ["97","98","99"]
#df = pd.read_csv('sample_data/covid.csv',na_values = missing_values)

#df.describe()

# original!
# drop missing values
#intermediatedf = df.dropna()
#intermediatedf.describe()

# all sex = 1 and all patient_type = 2, drop the first two columns: only focus on female inpatient
# we don't care about id: drop it

df = df.drop(['id','sex','patient_type'], axis = 1) 

df.describe()
df.head()

# New column fatality: Yes-dead; No-Recovered
# df['fatality'] = np.where(df['date_died'] != '9999-99-99', 'Yes', 'No')
df['fatality'] = np.where(df['date_died'] != '9999-99-99', 1, 2)

# calculate entry - symptoms; only include valid records
df['entry_symptoms'] = pd.DataFrame(pd.to_datetime(df['entry_date']) - pd.to_datetime(df['date_symptoms']))

# dropping units
df['entry_symptoms'] = pd.to_numeric(df['entry_symptoms'].astype(str).str[:-4], errors='coerce')

# only include valid records
df = df[df['entry_symptoms'] >= 0]

df.head()

# drop useless columns
df = df.drop(['entry_date','date_symptoms','date_died'], axis = 1) 

df.describe()

df.to_csv(path_or_buf="data_half_ready.csv")

plt.boxplot(x = df["age"], 
 
            patch_artist=True, 
 
            showmeans=True, 
 
            boxprops = {'color':'black','facecolor':'#9999ff'}, 
 
            flierprops = {'marker':'o','markerfacecolor':'red','color':'black'}, 
 
            meanprops = {'marker':'D','markerfacecolor':'indianred'}, 
 
            medianprops = {'linestyle':'--','color':'orange'}) 

plt.show()

conditions = [
    (df['entry_symptoms'] <= 1),
    (df['entry_symptoms'] > 1) & (df['entry_symptoms'] <= 3),
    (df['entry_symptoms'] > 3) & (df['entry_symptoms'] <= 5),
    (df['entry_symptoms'] > 5) & (df['entry_symptoms'] <= 10),
    (df['entry_symptoms'] > 10)
    ]

values = ['0', '1', '3', '5','10']

df['date_diff_level'] = np.select(conditions, values)

plt.hist(df['date_diff_level'], edgecolor='k', alpha=0.35) # 设置直方边线颜色为黑色，不透明度为 0.35
plt.show()

df.head()

# no longer need entry-symptoms: drop column
df = df.drop(['entry_symptoms'], axis = 1) 

df.head()

# df['intubed'] = np.where(df['intubed'] == 1, 'Yes', 'No')
# df['pneumonia'] = np.where(df['pneumonia'] == 1, 'Yes', 'No')
# df['pregnancy'] = np.where(df['pregnancy'] == 1, 'Yes', 'No')
# df['diabetes'] = np.where(df['diabetes'] == 1, 'Yes', 'No')
# df['copd'] = np.where(df['copd'] == 1, 'Yes', 'No')
# df['asthma'] = np.where(df['asthma'] == 1, 'Yes', 'No')
# df['inmsupr'] = np.where(df['inmsupr'] == 1, 'Yes', 'No')
# df['hypertension'] = np.where(df['hypertension'] == 1, 'Yes', 'No')
# df['other_disease'] = np.where(df['other_disease'] == 1, 'Yes', 'No')
# df['cardiovascular'] = np.where(df['cardiovascular'] == 1, 'Yes', 'No')
# df['obesity'] = np.where(df['obesity'] == 1, 'Yes', 'No')
# df['renal_chronic'] = np.where(df['renal_chronic'] == 1, 'Yes', 'No')
# df['tobacco'] = np.where(df['tobacco'] == 1, 'Yes', 'No')
# df['contact_other_covid'] = np.where(df['contact_other_covid'] == 1, 'Yes', 'No')
# df['icu'] = np.where(df['icu'] == 1, 'Yes', 'No')

# df['intubed'] = np.where(df['intubed'] == 1, 0, 1)
# df['pneumonia'] = np.where(df['pneumonia'] == 1, 0, 1)
# df['pregnancy'] = np.where(df['pregnancy'] == 1, 0, 1)
# df['diabetes'] = np.where(df['diabetes'] == 1, 0, 1)
# df['copd'] = np.where(df['copd'] == 1, 0, 1)
# df['asthma'] = np.where(df['asthma'] == 1, 0, 1)
# df['inmsupr'] = np.where(df['inmsupr'] == 1, 0, 1)
# df['hypertension'] = np.where(df['hypertension'] == 1, 0, 1)
# df['other_disease'] = np.where(df['other_disease'] == 1, 0, 1)
# df['cardiovascular'] = np.where(df['cardiovascular'] == 1, 0, 1)
# df['obesity'] = np.where(df['obesity'] == 1, 0, 1)
# df['renal_chronic'] = np.where(df['renal_chronic'] == 1, 0, 1)
# df['tobacco'] = np.where(df['tobacco'] == 1, 0, 1)
# df['contact_other_covid'] = np.where(df['contact_other_covid'] == 1, 0, 1)
# df['icu'] = np.where(df['icu'] == 1, 0, 1)

df.head()

# new_conditions = [(df['covid_res'] == 1),(df['covid_res'] == 2),(df['covid_res'] == 3)]
# new_values = ['Positive', 'Negative', 'Waiting']
# df['covid_res'] = np.select(new_conditions, new_values)
df.describe()

df.to_csv(path_or_buf="data_ready.csv")

df.fatality.unique()

# #split x and y, split train set and test set
# y = df['fatality']
# x = df.drop('fatality',axis = 1)
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# x_train.head

# # random forest
# #kfold = StratifiedKFold(n_splits=20)
# model = RandomForestClassifier()
# rf_param_grid = {"max_depth": [None],
#                 #  "max_features": [1, 5, 9, 13, 17],
#               "min_samples_split": [6, 7, 8, 9], # 7
#               "min_samples_leaf": [15, 20, 30, 50], # 20
#               "n_estimators" :[500,1000,2000], # 500
#               "criterion": ["gini"]}
# gsmodel = GridSearchCV(model,param_grid = rf_param_grid, scoring="accuracy", n_jobs= 1, verbose = 1)
# gsmodel.fit(x,y)
# model_best = gsmodel.best_estimator_
# print(model_best)
# print(gsmodel.best_score_)

y = df['fatality']
x = df.drop('fatality',axis = 1)

# all default
rf0 = RandomForestClassifier(oob_score=True, random_state=10)
rf0.fit(x,y)
print(rf0.oob_score_)
y_predprob = rf0.predict_proba(x)[:,1]
print("AUC Score (Train): %f" % metrics.roc_auc_score(y, y_predprob))

param_test1 = {'n_estimators':range(10,201,10)}
gsearch1 = GridSearchCV(estimator = RandomForestClassifier(min_samples_split=100,
                                  min_samples_leaf=20,max_depth=8,max_features='sqrt' ,random_state=10), 
                       param_grid = param_test1, scoring='roc_auc',cv=5)
gsearch1.fit(x,y)
print(gsearch1.cv_results_, gsearch1.best_params_, gsearch1.best_score_)

param_test2 = {'max_depth':range(5,25,2), 'min_samples_split':range(150,500,20)}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 130, 
                                  min_samples_leaf=20,max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test2, scoring='roc_auc',iid=False, cv=5)
gsearch2.fit(x,y)
gsearch2.cv_results_, gsearch2.best_params_, gsearch2.best_score_

param_test3 = {'min_samples_split':range(150,500,20), 'min_samples_leaf':range(5,100,5)}
gsearch3 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 130, max_depth=5,
                                  max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test3, scoring='roc_auc',iid=False, cv=5)
gsearch3.fit(x,y)
gsearch3.cv_results_, gsearch3.best_params_, gsearch3.best_score_

param_test4 = {'max_features':range(2,30,1)}
gsearch4 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 130, max_depth=5, min_samples_split=150,
                                  min_samples_leaf=5 ,oob_score=True, random_state=10),
   param_grid = param_test4, scoring='roc_auc',iid=False, cv=5)
gsearch4.fit(x,y)
gsearch4.cv_results_, gsearch4.best_params_, gsearch4.best_score_

rf2 = RandomForestClassifier(n_estimators= 130, max_depth=5, min_samples_split=150,
                                  min_samples_leaf=5,max_features=14 ,oob_score=True, random_state=10)
rf2.fit(x,y)
rf2.oob_score_

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

dt = DecisionTreeClassifier() # default tree
dt.fit(x_train,y_train) 
dt.predict(x_test)

dt.score(x_test, y_test)

dt1 = DecisionTreeClassifier(random_state = 66)
score = cross_val_score(dt1,x_train,y_train,cv=10).mean()
print('gini score: %.5f'%score)
dt2 = DecisionTreeClassifier(criterion = 'entropy',random_state = 66)
score = cross_val_score(dt2,x_train,y_train,cv=10).mean()
print('entropy score: %.5f'%score)

"""It can be seen above that the result using entropy is slightly better than using gini."""

# draw the plot for parameter:max_depth
ScoreAll = []
for i in range(1,100,10):
    dt = DecisionTreeClassifier(criterion = 'entropy',max_depth = i,random_state = 66)
    score = cross_val_score(dt,x,y,cv=10).mean()
    ScoreAll.append([i,score])
ScoreAll = np.array(ScoreAll)

max_score = np.where(ScoreAll==np.max(ScoreAll[:,1]))[0][0]
print("best parameter and score:",ScoreAll[max_score])  
# print(ScoreAll[,0])
plt.figure(figsize=[20,5])
plt.plot(ScoreAll[:,0],ScoreAll[:,1])
plt.show()

param = {'criterion':['gini'],'max_depth':[15,20,30,50,60,100],'min_samples_leaf':[2,3,5,10],'min_impurity_decrease':[0.1,0.2,0.5,0.7]}
grid = GridSearchCV(DecisionTreeClassifier(),param_grid=param,cv=10)
grid.fit(x_train,y_train)
print('best classifier:',grid.best_params_,'best score:', grid.best_score_)

dt3 = DecisionTreeClassifier(max_depth=15,min_samples_leaf=2,min_impurity_decrease=0.1)
dt3.fit(x_train,y_train)
y_pred = dt3.predict(x_test)
print('train set score', dt3.score(x_train,y_train),'test set score',dt3.score(x_test,y_test))